name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies for chromedp
      run: sudo apt-get install -y libnspr4 libnss3 libexpat1 libfontconfig1 libuuid1

    
    - name: Start containers (PostgreSQL, MongoDB, Redis)
      run: docker-compose -f "docker-compose-unittest.yml" up -d

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    
    - name: Setup .env file (mongo)
      run: mv .gh-actions-env .env

    - name: Build
      run: make build

    - name: Test (Mongo data store)
      run: make alltest
    
    - name: Change DATA_STORE to PostgreSQL
      run: sed -i 's/DATA_STORE=mongo/DATA_STORE=pg/g' .env
    
    - name: Change DATABASE_URL to PG connection string
      run: sed -i 's/DATABASE_URL=mongodb:\/\/localhost:27017/DATABASE_URL=user=postgres password=postgres dbname=postgres sslmode=disable/g' .env

    - name: Test (PostgreSQL data store)
      run: make alltest
